### ISSUE TITLE
Nothing happen when I try to validate the nonce

### ISSUE THREAD

**Issue by Teufeuleu** [GeoSn0w/GeoNonceSetter12#1]
Hi,
So I installed GeoNonceSetter12 with Impactor on an Iphone SE with 12.1.4 (
I launch the app, enter the nonce I got from my blob (0x1111111111111111), but then nothing happen when I hit Return or "Set Nonce Now!", I'm stuck at the same "write your nonce" step.
I also checked several times that I properly entered 16 times "1".

I also tried to upgrade to 12.2 using futurerestore and as expected I got the following error "Devicen ApNonce does not match APTicket nonce", so the nonce is well not set.

Any idea ?

**Comment by GeoSn0w** [comment]
New version should fix this.
