### ISSUE TITLE
Can't get tfp0

### ISSUE THREAD

**Issue by viktorkuts** [GeoSn0w/GeoNonceSetter12#3]
Hello, Im jailbroken with unc0ver ios 12.4 on iphone 8 and when I set my nonce (0x111...) and press set, it says can't get tfp0. I've downloaded it with Filza and appsync, didn't work. Sideloaded with Cydia Impactor, didn't work. Even tried rebooting to return to normal state and still the same error : Can't get tfp0.

**Comment by dontdeadopeninside** [comment]
Have this problem too.

**Comment by IainKay** [comment]
If you’ve jailbroken with unc0ver then it should, by default, have set the nonce generator to 0x1111111111111111. 

To confirm this open up unc0ver, click the settings cog in the top right and check that “Set Boot Nonce” is turned on. 

If so, no need for this app and your generator will be set.

**Comment by viktorkuts** [comment]
Wasn’t sure if was set. Issue closed.
